const actionTypes = {
  GET_MOVIES: 'GET_MOVIES',
  SORT_MOVIES: 'SORT_MOVIES',
  FILTER_MOVIES: 'FILTER_MOVIES',
  OPEN_ADD_MOVIE_MODAL: 'OPEN_ADD_MOVIE_MODAL',
  CLOSE_ADD_MOVIE_MODAL: 'CLOSE_ADD_MOVIE_MODAL',
  CLOSE_MOVIE_CARD: 'CLOSE_MOVIE_CARD',
  OPEN_MOVIE_CARD: 'OPEN_MOVIE_CARD',
  CLOSE_DELETE_MOVIE_MODAL: 'CLOSE_DELETE_MOVIE_MODAL',
  OPEN_DELETE_MOVIE_MODAL: 'OPEN_DELETE_MOVIE_MODAL',
  OPEN_EDIT_MOVIE_MODAL: 'OPEN_EDIT_MOVIE_MODAL',
  CLOSE_EDIT_MOVIE_MODAL: 'CLOSE_EDIT_MOVIE_MODAL',
  SEARCH_MOVIES: 'SEARCH_MOVIES'
}

export default actionTypes;

